version: "3.8"
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/javascript-node:22-bookworm
    volumes:
      - ../..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh:cached
    command: sleep infinity
